version: '2.0'
services:
  web:
    build: './front'
    ports:
      - "3000:3000"
    expose:
      - "3000"

  node:
    build: './back'
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - media-data:/data/media
    # environment:
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo
    restart: always
    #environment: # 환경 변수
    volumes:
      - mongo-data:/data/db
    container_name: "mongodb"
    ports:
      - "27017:27017"

volumes:
  media-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/media
      o: bind
  mongo-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind

    
