version: '2.0'
services:
  web:
    build: './front'
    ports:
      - "3000:3000"
    expose:
      - "3000"

  node:
    build: './back'
    restart: always
    ports:
      - "8080:8080"
    # environment:
    depends_on:
    - mongodb
    
  mongodb:
    image: mongo
    restart: always
    #environment: # 환경 변수
    volumes:
      - type: bind
        source: ./data/db
        target: /data/db
    container_name: "mongodb"
    ports:
      - "27017:27017"


    