version: '2.0'
services:
  web:
    build: './front'
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./front/src:/app/src:cached
    stdin_open: true
    environment: 
      - CHOKIDAR_USEPOLLING=true

  node:
    build: './back'
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - media-data:/data
    networks:
      - babybeaver-network
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo:4.4.1-bionic
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: babybeaver
      MONGO_INITDB_DATABASE: babybeaver
    volumes:
      - mongo-data:/data/db
    container_name: "mongodb"
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all"]   
    ports:
      - "27017:27017"
    networks:
      - babybeaver-network

volumes:
  media-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/media
      o: bind
  mongo-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind

networks:
  babybeaver-network:

