version: '2.0'
services:
  web:
    build: './front'
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./front/src:/app/src:cached
      - ./data/media:/data
    stdin_open: true
    environment: 
      - CHOKIDAR_USEPOLLING=true

  node:
    build: './back'
    restart: always
    env_file: .env
    environment: 
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    ports:
      - "5000:5000"
    volumes:
      - ./data/media:/data
      - ./back:/app
    networks:
      - babybeaver-network
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo:4.4.1-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    container_name: "mongodb"
    ports:
      - "27017:27017"
    networks:
      - babybeaver-network

volumes:
  media-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/media
      o: bind
  mongo-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/db
      o: bind

networks:
  babybeaver-network:

